name: Build Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.124.1'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Upload public folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: hugo-public
          path: public
