name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.119.0'
        extended: true

    - name: Build site
      run: hugo --minify

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Deploy to S3
      run: |
        # Sync files with optimized caching headers
        aws s3 sync public/ s3://${{ secrets.S3_BUCKET_NAME }} \
          --delete \
          --cache-control "max-age=31536000" \
          --exclude "*.html" \
          --exclude "*.xml" \
          --exclude "*.json"
        
        # Sync HTML files with shorter cache
        aws s3 sync public/ s3://${{ secrets.S3_BUCKET_NAME }} \
          --delete \
          --cache-control "max-age=3600" \
          --include "*.html" \
          --include "*.xml" \
          --include "*.json"

    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"